/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    private Object[] quoteArray;
    private App.Quote testQuote;
    private String quoteString;

    @Before
    public void initQuoteArray() throws Exception {
        App init = new App();
        new App.Quote("Richard", "hello");

        quoteString = App.getQuoteData();
        quoteArray = App.jsonToQuotes(quoteString);

        testQuote = new App.Quote("Richard Rider", "Please, please, you have to, I never ask you for anything, please just do it.");
        System.out.println("Quote Array was instanced.");
    }

    @Test
    public void testQuoteToString() {

        assertNotNull("printRandom object, when run on the entire array of JSON data, should return not null.",
                App.getRandomObject(quoteArray));
    }

    @Test
    public void testQuotePrint() {

        String expectedString = "Richard Rider: Please, please, you have to, I never ask you for anything, please just do it.";

        assertEquals("printRandomObject, when run on a single object should return a string equivalent to the string above.",
                expectedString,
                App.getRandomObject(new Object[] {testQuote})
        );
    }
}
